### ISSUE TITLE
ISO download fails

### ISSUE THREAD

**Issue by starship-boi** [JovarkOS/jovarkos-website#3]
The Download link at https://iso.jovarkos.org/latest/jovarkos-latest.iso that is triggered when clicking the "Download" button under the JovarkOS Beta heading produces the following browser error:

This site can’t provide a secure connectioniso.jovarkos.org sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

I was using Brave, but someone using a possibly different browser and OS in a different country received the same error.

**Comment by lucasburlingham** [comment]
Thanks. I hadn't gotten an SSL cert since I setup the ISO subdomain on the 7th.

**Comment by lucasburlingham** [comment]
Ran `certbot` as user `root` on Linode server "repo" with hostname `{repo,assets,iso}.jovarkos.org`. Expanded SSL certificate.

Visited site, downloaded file at https://iso.jovarkos.org/latest/jovarkos-latest.iso with approx speed 30MB/s, finishing in ~1 minute. No issues reported.


Issue resolved, closing.
